name: 'Cloudflared SSH Remote Acess'
branding:
  icon: 'terminal'
  color: 'orange'
description: 'Com essa ação é possivel utilizar o servidor com a Cloudflared tunnel'
inputs:
  host:
    description: 'SSH host address'
    required: true
  port:
    description: 'SSH port number'
    default: "22"
  username:
    description: 'SSH username'
  private_key:
    description: 'SSH private key'
  commands:
    description: 'The commands to run on the remote server'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.host }}
    - ${{ inputs.port }}
    - ${{ inputs.username }}
    - ${{ inputs.private_key }}
    - ${{ inputs.commands }}